/**
 * Unit tests for markdown-parser
 * Feature: 001-session-memory-file
 * Tasks: T040-T043
 */

import { describe, it, expect } from 'vitest';
import { parseMarkdown } from '@/lib/session-memory/markdown-parser';

const VALID_MARKDOWN = `# Session Memory: electromate

**Generated**: 2025-12-25T10:11:41.100Z
**Branch**: 001-session-memory-file

## Executive Summary

1. High-precision electrical engineering calculation platform
2. 43/100 tasks complete (43.0%)
3. Current phase: User Story 2 - Restore Project Context
4. Database connection requires configuration
5. Next action: Complete T044 E2E test implementation

## Task Status

**Source**: specs/001-session-memory-file/tasks.md

| Phase | Completed | Total | Percentage |
|-------|-----------|-------|------------|
| Setup | 4 | 4 | 100.0% |
| Foundational | 5 | 5 | 100.0% |
| User Story 1 | 30 | 30 | 100.0% |
| User Story 2 | 4 | 25 | 16.0% |

**Current Task**: T044 - E2E test for loading session memory

**Next Tasks**: T044, T045, T046, T047, T048

## Blockers

### High Priority

- Collect from TODO/FIXME comments
  - **Description**: Found in lib/session-memory/collectors/blocker-collector.ts:20
  - **Action**: Fix issue: Collect from TODO/comments

### Medium Priority

- **T032**: Database configuration missing
  - **Description**: NEON_DATABASE_URL not set in .env.local
  - **Action**: Create .env.local from template

## Test Results

**Last Run**: 2025-12-25T09:00:00.000Z

### Unit Tests (Vitest)

- **Status**: ✅ 45/45 passing (100.0%)
- **Command**: \`npm test\`

### E2E Tests (Playwright)

- **Status**: Not run
- **Command**: \`npm run test:e2e\`

## Environment State

### Development Servers

No active development servers detected.

### Dependencies

- **Status**: up-to-date
- **Last Install**: 2025-12-24T22:15:54.246Z
- **Package Manager**: npm

### Build Status

- **Status**: success
- **Last Build**: 2025-12-24T22:19:12.385Z
- **Output**: .next/

## Files Needing Attention

1. \`lib/session-memory/collectors/blocker-collector.ts:20\` - TODO comment needs implementation
2. \`components/battery/BatteryCalculator.tsx:51\` - Type mapping incomplete

## Next Steps

1. **Immediate**: Fix issue: Collect from TODO/comments
2. **Short-term**: Complete T044 E2E test (T044)
3. **Medium-term**: Implement markdown parser sections
4. **Long-term**: Add CLI command integration

---

*Generated by Claude Code Session Memory v1.0*`;

describe('Markdown Parser', () => {
  describe('T040: Parse valid markdown back to SessionMemory', () => {
    it('should parse complete valid markdown file', () => {
      const result = parseMarkdown(VALID_MARKDOWN);

      expect(result).toBeDefined();
      expect(result.metadata).toBeDefined();
      expect(result.summary).toBeDefined();
      expect(result.taskStatus).toBeDefined();
      expect(result.blockers).toBeDefined();
      expect(result.testResults).toBeDefined();
      expect(result.environment).toBeDefined();
      expect(result.filesNeedingAttention).toBeDefined();
      expect(result.nextSteps).toBeDefined();
    });

    it('should parse metadata correctly', () => {
      const result = parseMarkdown(VALID_MARKDOWN);

      expect(result.metadata.projectName).toBe('electromate');
      expect(result.metadata.generatedAt).toBe('2025-12-25T10:11:41.100Z');
      expect(result.metadata.branch).toBe('001-session-memory-file');
      expect(result.metadata.version).toBe('1.0');
    });

    it('should parse executive summary correctly', () => {
      const result = parseMarkdown(VALID_MARKDOWN);

      expect(result.summary.projectDescription).toBe('High-precision electrical engineering calculation platform');
      expect(result.summary.completionStatus).toBe('43/100 tasks complete (43.0%)');
      expect(result.summary.currentPhase).toBe('User Story 2 - Restore Project Context');
      expect(result.summary.majorBlocker).toBe('Database connection requires configuration');
      expect(result.summary.nextAction).toBe('Complete T044 E2E test implementation');
    });

    it('should parse task status correctly', () => {
      const result = parseMarkdown(VALID_MARKDOWN);

      expect(result.taskStatus.sourceFile).toBe('specs/001-session-memory-file/tasks.md');
      expect(result.taskStatus.phases).toHaveLength(4);
      expect(result.taskStatus.phases[0]).toEqual({
        name: 'Setup',
        completed: 4,
        total: 4,
        percentage: 100.0,
      });
      expect(result.taskStatus.currentTask?.id).toBe('T044');
      expect(result.taskStatus.nextTasks).toHaveLength(5);
    });

    it('should parse blockers correctly', () => {
      const result = parseMarkdown(VALID_MARKDOWN);

      expect(result.blockers.length).toBeGreaterThanOrEqual(2);

      const highBlocker = result.blockers.find((b) => b.priority === 'high');
      expect(highBlocker).toBeDefined();
      expect(highBlocker?.title).toContain('TODO/FIXME');

      const mediumBlocker = result.blockers.find((b) => b.priority === 'medium');
      expect(mediumBlocker).toBeDefined();
      expect(mediumBlocker?.taskId).toBe('T032');
    });

    it('should parse test results correctly', () => {
      const result = parseMarkdown(VALID_MARKDOWN);

      expect(result.testResults.lastRun).toBe('2025-12-25T09:00:00.000Z');
      expect(result.testResults.unit.status).toBe('passed');
      expect(result.testResults.unit.passed).toBe(45);
      expect(result.testResults.unit.total).toBe(45);
      expect(result.testResults.unit.percentage).toBe(100.0);
      expect(result.testResults.e2e.status).toBe('not-run');
    });

    it('should parse environment state correctly', () => {
      const result = parseMarkdown(VALID_MARKDOWN);

      expect(result.environment.servers).toHaveLength(0);
      expect(result.environment.dependencies.status).toBe('up-to-date');
      expect(result.environment.dependencies.packageManager).toBe('npm');
      expect(result.environment.build.status).toBe('success');
      expect(result.environment.build.outputDir).toBe('.next/');
    });

    it('should parse files needing attention correctly', () => {
      const result = parseMarkdown(VALID_MARKDOWN);

      expect(result.filesNeedingAttention).toHaveLength(2);
      expect(result.filesNeedingAttention[0].path).toBe('lib/session-memory/collectors/blocker-collector.ts');
      expect(result.filesNeedingAttention[0].line).toBe(20);
    });

    it('should parse next steps correctly', () => {
      const result = parseMarkdown(VALID_MARKDOWN);

      expect(result.nextSteps).toHaveLength(4);
      expect(result.nextSteps[0].priority).toBe('immediate');
      expect(result.nextSteps[1].priority).toBe('short-term');
      expect(result.nextSteps[2].priority).toBe('medium-term');
      expect(result.nextSteps[3].priority).toBe('long-term');
    });
  });

  describe('T041: Handle corrupted files with missing sections', () => {
    it('should return partial data for missing executive summary', () => {
      const partialMarkdown = `# Session Memory: test-project

**Generated**: 2025-12-25T10:00:00Z
**Branch**: main

## Task Status

**Source**: tasks.md

## Blockers

No blockers identified.

## Test Results

### Unit Tests (Vitest)

- **Status**: Not run
- **Command**: \`npm test\`

### E2E Tests (Playwright)

- **Status**: Not run
- **Command**: \`npm run test:e2e\`

## Environment State

### Development Servers

No active development servers detected.

### Dependencies

- **Status**: unknown
- **Package Manager**: npm

### Build Status

- **Status**: not-run

## Files Needing Attention

No files requiring attention.

## Next Steps

No recommended actions at this time.`;

      const result = parseMarkdown(partialMarkdown);

      expect(result.metadata.projectName).toBe('test-project');
      expect(result.summary.projectDescription).toBe('');
      expect(result.taskStatus.sourceFile).toBe('tasks.md');
    });

    it('should handle empty blockers section', () => {
      const result = parseMarkdown(VALID_MARKDOWN.replace(
        /## Blockers[\s\S]*?(?=## Test Results)/,
        '## Blockers\n\nNo blockers identified.\n\n'
      ));

      expect(result.blockers).toHaveLength(0);
    });

    it('should handle missing files needing attention', () => {
      const result = parseMarkdown(VALID_MARKDOWN.replace(
        /## Files Needing Attention[\s\S]*?(?=## Next Steps)/,
        '## Files Needing Attention\n\nNo files requiring attention.\n\n'
      ));

      expect(result.filesNeedingAttention).toHaveLength(0);
    });
  });

  describe('T042: Handle invalid timestamps', () => {
    it('should preserve invalid timestamp as string (validation done elsewhere)', () => {
      const invalidTimestamp = VALID_MARKDOWN.replace(
        '2025-12-25T10:11:41.100Z',
        'invalid-date'
      );

      const result = parseMarkdown(invalidTimestamp);

      // Parser preserves the value, validation happens in validator.ts
      expect(result.metadata.generatedAt).toBe('invalid-date');
    });

    it('should handle missing timestamp gracefully', () => {
      const noTimestamp = `# Session Memory: test

**Branch**: main

## Executive Summary

1. Test project
2. 0/0 tasks
3. Current phase: None
4. No critical blockers
5. Next action: Start development

## Task Status

**Source**: tasks.md

## Blockers

No blockers identified.

## Test Results

### Unit Tests (Vitest)

- **Status**: Not run
- **Command**: \`npm test\`

### E2E Tests (Playwright)

- **Status**: Not run
- **Command**: \`npm run test:e2e\`

## Environment State

### Development Servers

No active development servers detected.

### Dependencies

- **Status**: unknown
- **Package Manager**: npm

### Build Status

- **Status**: not-run

## Files Needing Attention

No files requiring attention.

## Next Steps

No recommended actions at this time.`;

      const result = parseMarkdown(noTimestamp);

      // Should have a default timestamp (current time)
      expect(result.metadata.generatedAt).toBeTruthy();
    });
  });

  describe('T043: Validation of parsed data', () => {
    it('should parse percentages correctly (0-100 range)', () => {
      const result = parseMarkdown(VALID_MARKDOWN);

      for (const phase of result.taskStatus.phases) {
        expect(phase.percentage).toBeGreaterThanOrEqual(0);
        expect(phase.percentage).toBeLessThanOrEqual(100);
      }
    });

    it('should parse ISO 8601 timestamps', () => {
      const result = parseMarkdown(VALID_MARKDOWN);

      // Check format matches ISO 8601
      expect(result.metadata.generatedAt).toMatch(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/);
    });

    it('should parse priority values correctly', () => {
      const result = parseMarkdown(VALID_MARKDOWN);

      for (const blocker of result.blockers) {
        expect(['high', 'medium', 'low']).toContain(blocker.priority);
      }

      for (const step of result.nextSteps) {
        expect(['immediate', 'short-term', 'medium-term', 'long-term']).toContain(step.priority);
      }
    });

    it('should preserve relative paths', () => {
      const result = parseMarkdown(VALID_MARKDOWN);

      expect(result.taskStatus.sourceFile).not.toMatch(/^[A-Z]:\\/); // Not absolute Windows path
      expect(result.taskStatus.sourceFile).not.toMatch(/^\//); // Not absolute Unix path
    });
  });
});

describe('Edge Cases', () => {
  it('should handle empty markdown', () => {
    const result = parseMarkdown('');

    expect(result.metadata.projectName).toBe('unknown');
    expect(result.blockers).toHaveLength(0);
    expect(result.nextSteps).toHaveLength(0);
  });

  it('should handle markdown with only header', () => {
    const result = parseMarkdown('# Session Memory: minimal');

    expect(result.metadata.projectName).toBe('minimal');
  });

  it('should handle servers section with active servers', () => {
    const withServers = VALID_MARKDOWN.replace(
      'No active development servers detected.',
      '- ✅ **node**: running on port 3000\n  - **URL**: http://localhost:3000'
    );

    const result = parseMarkdown(withServers);

    expect(result.environment.servers.length).toBeGreaterThanOrEqual(1);
    expect(result.environment.servers[0].process).toBe('node');
    expect(result.environment.servers[0].port).toBe(3000);
  });

  it('should handle failed test suite', () => {
    const withFailures = VALID_MARKDOWN.replace(
      '- **Status**: ✅ 45/45 passing (100.0%)',
      '- **Status**: ❌ 40/45 passing (88.9%)\n- **Failed**:\n  - `test.ts:10` - should work'
    );

    const result = parseMarkdown(withFailures);

    expect(result.testResults.unit.status).toBe('failed');
    expect(result.testResults.unit.passed).toBe(40);
    expect(result.testResults.unit.failed).toBe(5);
  });
});
