// PDF Generator for Short Circuit Analysis

import jsPDF from 'jspdf'
import type { ShortCircuitInput, ShortCircuitCalculationResults, ShortCircuitProjectInfo } from '@/types/short-circuit'

interface ShortCircuitPDFInput {
  input: ShortCircuitInput
  results: ShortCircuitCalculationResults
  project: ShortCircuitProjectInfo
}

export async function downloadShortCircuitPDF(data: ShortCircuitPDFInput): Promise<void> {
  const { input, results, project } = data
  const doc = new jsPDF()
  let y = 20

  const addLine = (text: string, size = 10, bold = false) => {
    if (y > 270) { doc.addPage(); y = 20 }
    doc.setFontSize(size)
    doc.setFont('helvetica', bold ? 'bold' : 'normal')
    doc.text(text, 14, y)
    y += size * 0.5 + 2
  }

  const addRow = (label: string, value: string) => {
    if (y > 270) { doc.addPage(); y = 20 }
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.text(label, 14, y)
    doc.text(value, 100, y)
    y += 5
  }

  // Header
  addLine('Short Circuit Analysis Report', 16, true)
  addLine('ElectroMate Engineering Calculations', 9)
  y += 2

  // Project
  if (project.projectName || project.engineerName) {
    addLine('Project Information', 11, true)
    if (project.projectName) addRow('Project:', project.projectName)
    if (project.projectLocation) addRow('Location:', project.projectLocation)
    if (project.engineerName) addRow('Engineer:', project.engineerName)
    addRow('Date:', new Date().toLocaleDateString())
    addRow('Standard:', input.standard)
    y += 3
  }

  // System Parameters
  addLine('System Parameters', 11, true)
  addRow('System Voltage:', `${input.systemVoltage.toLocaleString()} V`)
  addRow('Phase:', input.phase)
  addRow('Frequency:', `${input.frequency} Hz`)
  addRow('Grounding:', input.grounding)
  addRow('Utility Fault MVA:', `${input.utilityFaultMVA} MVA`)
  addRow('Utility X/R Ratio:', `${input.utilityXRRatio}`)
  if (input.hasTransformer) {
    addRow('Transformer:', `${input.transformerKVA} kVA, %Z=${input.transformerImpedancePercent}%, X/R=${input.transformerXRRatio}`)
  }
  if (input.hasMotorContribution) {
    addRow('Motor Contribution:', `${input.totalMotorHP} HP (${input.motorType})`)
  }
  if (input.hasCableImpedance) {
    addRow('Cable:', `${input.cableLength}m, R=${input.cableResistance} X=${input.cableReactance} ohm/km`)
  }
  y += 3

  // Impedance
  addLine('System Impedance', 11, true)
  results.impedanceSummary.components.forEach(c => {
    addRow(c.name + ':', `R=${c.resistanceOhm.toFixed(5)} X=${c.reactanceOhm.toFixed(5)} Z=${c.impedanceOhm.toFixed(5)} ohm`)
  })
  addRow('Total:', `R=${results.impedanceSummary.totalResistanceOhm.toFixed(5)} X=${results.impedanceSummary.totalReactanceOhm.toFixed(5)} Z=${results.impedanceSummary.totalImpedanceOhm.toFixed(5)} ohm`)
  addRow('System X/R:', `${results.impedanceSummary.systemXRRatio}`)
  y += 3

  // Fault Currents
  addLine('Fault Current Results', 11, true)
  results.faultCurrents.forEach(fc => {
    addRow(fc.faultTypeLabel + ':', '')
    addRow('  Symmetrical RMS:', `${fc.symmetricalRMSKA} kA`)
    addRow('  Peak:', `${fc.peakKA} kA`)
    addRow('  Asymmetrical RMS:', `${fc.asymmetricalRMSKA} kA`)
    addRow('  Breaking:', `${fc.breakingCurrentKA} kA`)
  })
  y += 3

  // Asymmetry
  addLine('Asymmetry Factors', 11, true)
  addRow('Peak Factor (kp):', `${results.asymmetryFactors.peakFactor}`)
  addRow('Asymmetry Factor:', `${results.asymmetryFactors.asymmetryFactor}`)
  addRow('DC Time Constant:', `${results.asymmetryFactors.dcDecayTimeConstant} ms`)
  y += 3

  // Breaker
  addLine('Breaker Requirement', 11, true)
  addRow('Min Interrupting:', `${results.breakerAdequacy.requiredBreakingCapacityKA} kA`)
  addRow('Recommended:', results.breakerAdequacy.recommendedBreakerRating)
  addRow('Reference:', results.breakerAdequacy.codeReference)
  y += 3

  // Alerts
  if (results.alerts.length > 0) {
    addLine('Alerts & Notes', 11, true)
    results.alerts.forEach(alert => {
      const prefix = alert.type === 'error' ? 'ERROR' : alert.type === 'warning' ? 'WARNING' : 'INFO'
      addRow(`[${prefix}]`, alert.message)
    })
  }

  // Footer
  y += 5
  doc.setFontSize(7)
  doc.setFont('helvetica', 'italic')
  doc.text('Generated by ElectroMate - For reference only. Verify with qualified engineer.', 14, y)

  doc.save(`short-circuit-analysis-${input.systemVoltage}V-${new Date().toISOString().slice(0, 10)}.pdf`)
}
