// PDF Generator for Voltage Drop Calculator

import jsPDF from 'jspdf'
import type { VoltageDropInput, VoltageDropCalculationResults, VoltageDropProjectInfo } from '@/types/voltage-drop'

interface VoltageDropPDFInput {
  input: VoltageDropInput
  results: VoltageDropCalculationResults
  project: VoltageDropProjectInfo
}

export async function downloadVoltageDropPDF(data: VoltageDropPDFInput): Promise<void> {
  const { input, results, project } = data
  const { result, cableSuggestions, alerts } = results
  const doc = new jsPDF()
  let y = 20

  const addLine = (text: string, size = 10, bold = false) => {
    if (y > 270) { doc.addPage(); y = 20 }
    doc.setFontSize(size)
    doc.setFont('helvetica', bold ? 'bold' : 'normal')
    doc.text(text, 14, y)
    y += size * 0.5 + 2
  }

  const addRow = (label: string, value: string) => {
    if (y > 270) { doc.addPage(); y = 20 }
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.text(label, 14, y)
    doc.text(value, 100, y)
    y += 5
  }

  // Header
  addLine('Voltage Drop Analysis Report', 16, true)
  addLine('ElectroMate Engineering Calculations', 9)
  y += 2

  // Project
  if (project.projectName || project.engineerName) {
    addLine('Project Information', 11, true)
    if (project.projectName) addRow('Project:', project.projectName)
    if (project.projectLocation) addRow('Location:', project.projectLocation)
    if (project.engineerName) addRow('Engineer:', project.engineerName)
    addRow('Date:', new Date().toLocaleDateString())
    addRow('Standard:', input.standard)
    y += 3
  }

  // Input Parameters
  addLine('Input Parameters', 11, true)
  addRow('System Voltage:', `${input.systemVoltage} V`)
  addRow('Phase:', input.phase)
  addRow('Load Current:', `${input.current} A`)
  addRow('Length:', `${input.length} ${input.lengthUnit}`)
  addRow('Conductor Type:', input.conductorType === 'busway' ? 'Busway (Busbar Trunking)' : 'Cable')
  addRow('Material:', input.conductorMaterial)

  if (input.conductorType === 'cable') {
    if (input.cableSizeMode === 'select') {
      addRow('Cable Size:', input.standard === 'IEC' ? `${input.cableSizeMm2} mm²` : `${input.cableSizeAWG} AWG`)
    } else {
      addRow('Custom Resistance:', `${input.customResistance} ${input.standard === 'IEC' ? 'mV/A/m' : 'Ohm/1000ft'}`)
    }
    if (input.parallelRuns > 1) addRow('Parallel Runs:', `${input.parallelRuns}`)
  } else {
    addRow('Busway Type:', input.buswayType)
    if (input.buswayRating) addRow('Busway Rating:', `${input.buswayRating} A`)
    if (input.customBuswayImpedance) addRow('Custom Impedance:', `${input.customBuswayImpedance} mOhm/m`)
    addRow('Power Factor:', `${input.powerFactor}`)
  }

  addRow('Max Allowed Drop:', `${input.maxDropPercent}%`)
  y += 3

  // Results
  addLine('Calculation Results', 11, true)
  addRow('Voltage Drop:', `${result.voltageDrop} V (${result.voltageDropPercent}%)`)
  addRow('Receiving End Voltage:', `${result.receivingEndVoltage} V`)
  addRow('Conductor:', result.conductorDescription)
  addRow('Resistance:', `${result.resistance} ${result.resistanceUnit}`)
  if (result.reactance !== null) {
    addRow('Reactance:', `${result.reactance} ${result.resistanceUnit}`)
  }
  addRow('Circuit Multiplier:', `${result.circuitMultiplier}`)
  addRow('Current per Run:', `${result.currentPerRun} A`)
  addRow('Status:', result.isWithinLimit ? `PASS - Within ${result.limitPercent}% limit` : `FAIL - Exceeds ${result.limitPercent}% limit`)
  addRow('Reference:', result.standardReference)
  y += 3

  // Cable Suggestions
  if (cableSuggestions.length > 0) {
    addLine('Recommended Cable Sizes', 11, true)
    cableSuggestions.forEach(s => {
      const label = s.isOptimal ? '[OPTIMAL]' : '         '
      addRow(`${label} ${s.sizeMm2}mm²${s.sizeAWG ? ` (${s.sizeAWG})` : ''}`, `${s.voltageDropPercent}% (${s.voltageDrop}V)`)
    })
    y += 3
  }

  // Alerts
  if (alerts.length > 0) {
    addLine('Alerts & Notes', 11, true)
    alerts.forEach(alert => {
      const prefix = alert.type === 'error' ? 'ERROR' : alert.type === 'warning' ? 'WARNING' : 'INFO'
      addRow(`[${prefix}]`, alert.message)
    })
  }

  // Footer
  y += 5
  doc.setFontSize(7)
  doc.setFont('helvetica', 'italic')
  doc.text('Generated by ElectroMate - For reference only. Verify with qualified engineer.', 14, y)

  doc.save(`voltage-drop-${input.systemVoltage}V-${input.current}A-${new Date().toISOString().slice(0, 10)}.pdf`)
}
